src/Entity/Show.php
<?php

namespace App\Entity;

use App\Repository\ShowRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ShowRepository::class)
 * @ORM\Table(name="`show`")
 */
class Show
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $summary;

    /**
     * @ORM\Column(type="date")
     */
    private $show_date;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $adult_price;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $child_price;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $group_price;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="performance")
     */
    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity=Artist::class, mappedBy="shows")
     */
    private $artists;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->artists = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }

    public function getShowDate(): ?\DateTimeInterface
    {
        return $this->show_date;
    }

    public function setShowDate(\DateTimeInterface $show_date): self
    {
        $this->show_date = $show_date;

        return $this;
    }

    public function getAdultPrice(): ?int
    {
        return $this->adult_price;
    }

    public function setAdultPrice(?int $adult_price): self
    {
        $this->adult_price = $adult_price;

        return $this;
    }

    public function getChildPrice(): ?int
    {
        return $this->child_price;
    }

    public function setChildPrice(?int $child_price): self
    {
        $this->child_price = $child_price;

        return $this;
    }

    public function getGroupPrice(): ?int
    {
        return $this->group_price;
    }

    public function setGroupPrice(?int $group_price): self
    {
        $this->group_price = $group_price;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPerformance($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getPerformance() === $this) {
                $comment->setPerformance(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Artist[]
     */
    public function getArtists(): Collection
    {
        return $this->artists;
    }

    public function addArtist(Artist $artist): self
    {
        if (!$this->artists->contains($artist)) {
            $this->artists[] = $artist;
            $artist->addShow($this);
        }

        return $this;
    }

    public function removeArtist(Artist $artist): self
    {
        if ($this->artists->contains($artist)) {
            $this->artists->removeElement($artist);
            $artist->removeShow($this);
        }

        return $this;
    }
}

src/Form/ShowType.php
<?php

namespace App\Form;

use App\Entity\Artist;
use App\Entity\Show;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ShowType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('picture')
            ->add('summary')
            ->add('show_date')
            ->add('adult_price')
            ->add('child_price')
            ->add('group_price')
            ->add('artists')
        ;
        $builder->add('artists', EntityType::class, [
            'class' => Artist::class,
            'choice_label' => 'name',
            'expanded' => true,
            'multiple' => true,
            'by_reference' => false
        ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Show::class,
        ]);
    }
}

src/Controller/ShowController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Show;
use App\Form\CommentType;
use App\Form\ShowType;
use App\Repository\ShowRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/show")
 */
class ShowController extends AbstractController
{
    /**
     * @Route("/", name="show_index", methods={"GET"})
     */
    public function index(ShowRepository $showRepository): Response
    {
        return $this->render('show/index.html.twig', [
            'shows' => $showRepository->findAll(),
        ]);
    }

    /**
     * @Route("/prices", name="show_prices", methods={"GET"})
     */
    public function showPrices(ShowRepository $showRepository): Response
    {
        return $this->render('show/prices.html.twig', [
            'shows' => $showRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="show_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $show = new Show();
        $form = $this->createForm(ShowType::class, $show);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($show);
            $entityManager->flush();

            return $this->redirectToRoute('show_index');
        }

        return $this->render('show/new.html.twig', [
            'show' => $show,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="show_show", methods={"GET","POST"})
     */
    public function show(Show $show, Request $request): Response
    {
        $id = $show->getId();
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setPerformance($show);
            $user = $this->getUser();
            //dd($user);
            $comment->setAuthor($user);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($comment);
            $entityManager->flush();

            return $this->redirectToRoute('show_show', ['id' => $id]);
        }

        $comments = $show->getComments();

        return $this->render('show/show.html.twig', [
            'show' => $show,
            'comments' => $comments,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/{id}/edit", name="show_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Show $show): Response
    {
        $id = $show->getId();
        $form = $this->createForm(ShowType::class, $show);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('show_show', ['id' => $id]);
        }

        return $this->render('show/edit.html.twig', [
            'show' => $show,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="show_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Show $show): Response
    {
        if ($this->isCsrfTokenValid('delete'.$show->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($show);
            $entityManager->flush();
        }

        return $this->redirectToRoute('show_index');
    }
}

templates/show/_delete_form.html.twig
<form method="post" action="{{ path('show_delete', {'id': show.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ show.id) }}">
    <button class="btn btn-dark text-warning">Delete</button>
</form>

templates/show/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-dark text-warning mb-2">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/show/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Show{% endblock %}

{% block body %}
<div class="container-fluid bg-dark">
    <div class="mx-auto mt-5 col-sm-12 col-md-8">
        <div class="card bg-dark">
            <div class="contact-card card mb-5">
                <div class="container px-4">
                    <h3 class="mt-3">Edit Show</h3>
                    {{ include('show/_form.html.twig', {'button_label': 'Update'}) }}
                    <a href="{{ path('show_index') }}">back to list</a>
                    {{ include('show/_delete_form.html.twig') }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/show/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Show index{% endblock %}

{% block body %}
    <div class="card bg-dark">
        <div class="card-header bg-warning border-0 rounded-0">
            <h3 class="text-center text-dark pt-2">All shows</h3>
        </div>
    </div>
    <div>
        {% if is_granted('ROLE_ADMIN') %}
            <a href="{{ path('show_new') }}" class="btn btn-warning mt-4 ml-5" role="button" aria-pressed="true">Create new</a>
        {% endif %}
    </div>
    <div class="container bg-dark">
        <div class="row">
            {% for show in shows %}
                <div class="my-4 col-sm-6 col-md-5 col-lg-4">
                    <div class="card bg-warning">
                        <img src="{{ show.picture }}" class="card-img-top" alt="{{ show.title }}" style="height: 300px;">
                        <div class="card-body bg-dark text-warning">
                            <h4 class="card-title" style="height: 68px;">{{ show.title }}</h4>
                            <p class="card-text"><strong>Summary :</strong></p>
                            <p class="card-text" style="height: 150px;">{{ show.summary }}</p>
                        </div>
                        <div class="card-body bg-dark text-white">
                            <a href="{{ path('show_show', { 'id': show.id }) }}" class="card-link">Details</a>
                        </div>
                    </div>
                </div>
            {% else %}
                No show found.
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/show/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Show{% endblock %}

{% block body %}
    <div class="container-fluid bg-dark">
        <div class="mx-auto mt-5 col-sm-12 col-md-8">
            <div class="card bg-dark">
                <div class="contact-card card mb-5">
                    <div class="container px-4">
                        <h3 class="mt-3">Create new Show</h3>
                        {{ include('show/_form.html.twig') }}
                        <a href="{{ path('show_index') }}" class="mt-3">Back to list</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/show/prices.html.twig
{% extends 'base.html.twig' %}

{% block title %}Show index{% endblock %}

{% block body %}
    <div class="container prices-container bg-dark text-warning">
        <h4 class="py-3">Regular tickets</h4>
        <table class="table table-warning table-striped">
            <thead>
                <tr class="table-warning">
                    <th scope="col">Shows</th>
                    <th scope="col">Adults</th>
                    <th scope="col">Children under 12</th>
                    <th scope="col">Groups</th>
                </tr>
            </thead>
            <tbody>
            {% for show in shows %}
                <tr class="table-warning">
                    <th scope="row">{{ show.title }}</th>
                    <td>{{ show.adultPrice }} €</td>
                    <td>{{ show.childPrice }} €</td>
                    <td>{{ show.groupPrice }} €</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <h4 class="py-3">VIP experience</h4>
        <p>Enjoy exclusive perks in our VIP Suite and watch the show from Premium seats. <a class="prices-link" href="{{ path('contact') }}">Contact us</a></p>
        <h4 class="py-3">Premium Backstage Tour Package</h4>
        <p class="pb-3">Go behind the scenes for the very best of Wild Circus. <a class="prices-link" href="{{ path('contact') }}">Contact us</a></p>
    </div>
{% endblock %}

templates/show/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Show{% endblock %}

{% block body %}
    <div class="container-fluid bg-dark">
        <div class="mt-4 col-sm-12 col-md-12">
            <div class="card bg-dark border-warning">
                <div class="row no-gutters">
                    <div class="col-sm-12 col-md-5">
                        <img class="card-img-top mt-5 ml-3" src="{{show.picture}}" alt="{{ show.title }} poster">
                        {% if is_granted('ROLE_ADMIN') %}
                            <a href="{{ path('show_edit', {'id': show.id}) }}" class="btn btn-warning mt-5 ml-4" role="button" aria-pressed="true">Edit</a>
                            {{ include('show/_delete_form.html.twig') }}
                        {% endif %}
                    </div>
                    <div class="col-sm-10 col-md-7">
                        <div class="card-body">
                            <div class="card-body bg-dark text-warning">
                                <h2 class="card-title">{{ show.title }}</h2>
                                <a href="{{ path('show_index') }}">Back to all shows</a>
                                <p class="card-text mt-4"><strong>Summary :</strong></p>
                                <p class="card-text">{{ show.summary }}</p>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item bg-dark text-warning"><strong>Date : </strong>{{ show.showDate ? show.showDate|date('Y-m-d') : '' }}</li>
                                <li class="list-group-item bg-dark text-warning"><strong>Prices</strong></li>
                            </ul>
                            <p class="card-text bg-dark text-white ml-5 text-warning">Adult : {{ show.adultPrice }} €</p>
                            <p class="card-text bg-dark text-white ml-5 text-warning">Child : {{ show.childPrice }} €</p>
                            <p class="card-text bg-dark text-white ml-5 text-warning">Group : {{ show.groupPrice }} €</p>
                        </div>
                        <div class="card-body">
                            <div class="card-body bg-dark text-warning">
                                <h4 class="mb-4">Artists :</h4>
                                {% for artist in show.artists %}
                                    <div>
                                        <a href="{{ path('artist_show', { 'id': artist.id }) }}">{{ artist.name }}</a>
                                    </div>
                                    <br>
                                {% else %}
                                    No artist found.
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

<div class="container-fluid bg-dark">
    <div class="mt-4 col-sm-12 col-md-6">
        <div class="card bg-dark">
            <div class="contact-card card">
                <div class="container px-4">
                    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                        <h3 class="mt-3">Comments</h3>
                        <br>
                        <h4>Add a comment</h4>
                        {{ form_start(form) }}
                        {{ form_widget(form) }}
                        <button class="btn btn-dark text-warning mb-3">{{ button_label|default('Save') }}</button>
                        {{ form_end(form) }}
                        {#{{ include('comment/_form.html.twig') }}#}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid bg-dark">
    <div class="mt-5 col-sm-12 col-md-6">
            {% if is_granted('IS_AUTHENTICATED_FULLY') %}
            <ul>
                {% for comment in show.comments %}
                    <table class="table">
                        <tbody>
                        <tr class="text-warning">
                            <th>Comment # {{ comment.id }}</th>
                            <td></td>
                        </tr>
                        <tr class="text-warning">
                            <th>Comment</th>
                            <td>{{ comment.comment }}</td>
                        </tr>
                        <tr class="text-warning">
                            <th>Rate</th>
                            <td>{{ comment.rate }}</td>
                        </tr>
                        <tr class="text-warning">
                            <th>Author</th>
                            <td>{{ comment.author }}</td>
                        </tr>
                        </tbody>
                    </table>
                    {% if app.user.email == comment.author or is_granted('ROLE_ADMIN')%}
                        <a class="btn btn-warning mb-2" href="{{ path('comment_edit', {'id': comment.id}) }}">Edit</a>
                        {{ include('comment/_delete_form.html.twig') }}
                    {% endif %}
                    <br>
                {% else %}
                    <li class="text-warning mb-3">No comment</li>
                {% endfor %}
            </ul>
            {% endif %}
    </div>
</div>

{% endblock %}